coverage:
  range: 50...70 # Below, 50 red, 50-69 yellow, 70+ green
  round: down
  precision: 2
  status:
    project:
      default:
        threshold: 1%
parsers:
  v1:
    include_full_missed_files: true  # default false
ignore:
  - "scripts"
comment:
  layout: "diff, flags, files"